# Generated by Django 5.1.3 on 2025-01-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login2',
        ),
    ]
